// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/4f1ec2ec0e2afa12fd34f16051983dc430a27c29/scroll-into-view/scroll-into-view.d.ts
declare module __ScrollIntoView {

    interface Settings {
        time?: number
        ease?: (value: number) => number
        validTarget?: (target: HTMLElement, parentsScrolled: number) => boolean
        align?: Alignment
    }

    interface Alignment {
        /** 0 to 1, default 0.5 (center) */
        top?: number
        /** 0 to 1, default 0.5 (center) */
        left?: number
    }

    /** type will be 'complete' if the scroll completed or 'canceled' if the current scroll was canceled by a new scroll */
    type callbackParamterType = "complete" | "canceled"
    type Callback = (type: callbackParamterType) => void

    interface ScrollIntoView {
        (target: HTMLElement, callback?: __ScrollIntoView.Callback) : void
        (target: HTMLElement, settings: __ScrollIntoView.Settings, callback?: __ScrollIntoView.Callback) :  void
    }

}

declare module "scroll-into-view" {
    var scrollIntoView: __ScrollIntoView.ScrollIntoView
    export = scrollIntoView;
}
